### ISSUE TITLE
Error while training the subsample dataset

### ISSUE THREAD

**Issue by braum1989** [hukenovs/hagrid#10]
Need help, training always stops at step 22 and it shows this error below:

File "/usr/local/lib/python3.7/dist-packages/matplotlib/cm.py", line 477, in set_array
    raise TypeError(f"Image data of dtype {A.dtype} cannot be "
TypeError: Image data of dtype object cannot be converted to float

![image](https://user-images.githubusercontent.com/97431655/188141162-ba2f3a26-27ed-4f0b-b383-47cf9f3956d7.png)

Also, I'm still new to machine learning and was wondering where I should put the.pth file if I choose to train the datasets using a pretrained model.

**Comment by Wazz37** [comment]
@briantmorales did u got the answer?
