### ISSUE TITLE
Retraining SSDLite model

### ISSUE THREAD

**Issue by vccheng2001** [hukenovs/hagrid#11]
Hi,
Do you happen to have the training script for retraining the SSDLite classification head? I'd like to add another class.
For training, what should the targets consist of? Thanks!

**Comment by anotherhelloworld** [comment]
Hello, @vccheng2001, sorry for the long wait for a reply. 

We are going to publish SSDLite detector training pipeline soon. Also a similar question has already been raised in [this](https://github.com/hukenovs/hagrid/issues/9#issuecomment-1240475860) thread.
