### ISSUE TITLE
How to export SSDLite.pth to ONNX?

### ISSUE THREAD

**Issue by yangbohust** [hukenovs/hagrid#18]
How to export SSDLite.pth to ONNX?

**Comment by anotherhelloworld** [comment]
Hello, @yangbohust ! 

We create a [google collab notebook](https://colab.research.google.com/drive/1pfooFyBpL7D_pe_AJthwX_uE4hMCkGqU?usp=sharing) with an example of exporting our SSDLite model onnx format. Therefore, you can use this notebook to get a model in onnx format and modify this code as you wish.

**Comment by nagadit** [comment]
I am closing this issue, but feel free to reopen it if you feel like it has not been resolved.
