### ISSUE TITLE
Problems using pretrained ResNet-based models for gesture identification

### ISSUE THREAD

**Issue by MechaFear** [hukenovs/hagrid#20]
Hello,
first of all I wanted to thank you for the amazing work you did so far!
I open this issue to signal a problem occurring to me while trying to use the pretrained resnet-based models which weighs you made available for download. In particular the predictions made by the Linear model applied after the model "backbone" seem random, this because while the various components of the model backbone have their own pretrained weights, the final Linear layer is seemingly instantiated at random - I'm referring to the lines 68-70 found in "classifier/models/resnet.py".

Am I doing anything wrong or am I missing/misunderstanding something, or is it an oversight on your side?

Thanks for your attention.

**Comment by anotherhelloworld** [comment]
Hello, @MechaFear 

If you use our model and load our weights, then this means that all "backbone" and linear layers are initialized with the parameters of the model that we trained on our dataset.

**Comment by nagadit** [comment]
I am closing this issue, but feel free to reopen it if you feel like it has not been resolved.
