### ISSUE TITLE
Can't download subsample

### ISSUE THREAD

**Issue by rk6Github** [hukenovs/hagrid#21]
The link to download the subsample of images is broken (https://sc.link/AO5l). The download maxes out at 1 GB. Is there any way to fix this?

**Comment by XZLancer** [comment]
I also encountered this problem when downloading testset, hope it can be solved

**Comment by XZLancer** [comment]
> I also encountered this problem when downloading testset, hope it can be solved

The download link is available today :)

**Comment by nagadit** [comment]
Can you give more information @rk6Github @XZLancer 
Your country?
Your ISP?
What kind of error occurs after a 1GB download?

**Comment by XZLancer** [comment]
![screenshot](https://user-images.githubusercontent.com/29305079/206176382-26612325-d6d8-4be8-99ae-d6fc6ae1081c.jpg)
 I use wget to download the testset in China and it stuck at 1GB. Here is the screenshot of the error. By the way, I have successfully downloaded today, thank you for your reply.

**Comment by rk6Github** [comment]
I have also successfully downloaded since this post. Not sure what happened, thanks to everyone who responded
