### ISSUE TITLE
Something wrong happens when I try to use new dataset to test the pretrained model?

### ISSUE THREAD

**Issue by explorer66** [hukenovs/hagrid#22]
When I test the pretrained resnet18 with gesture images not in the test dataest,it seems that the model can't even recognize the simplest gestures like One,Ok and Six.
Here are the outputs of the model when I put into a new gesture picture into it.
`{'gesture': tensor([[ 0.0327,  0.0073,  0.0662, -0.0611,  0.0772,  0.1809,  0.0938,  0.1073,
         -0.0719, -0.1703,  0.2205, -0.1140, -0.1982,  0.1579, -0.3652, -0.2734,
          0.1343, -0.2151,  0.5438]], grad_fn=<AddmmBackward0>), 'leading_hand': tensor([[ 0.6901, -0.6721]], grad_fn=<AddmmBackward0>)}`

**Comment by anotherhelloworld** [comment]
Hello, @explorer66!

Can you please provide sample image with gesture on which you are testing ResNet18  or a link to it in this issue?

**Comment by anotherhelloworld** [comment]
Hello, @explorer66

Thank you for providing sample images. We create a [google collab notebook](https://colab.research.google.com/drive/1nXsDJGkD-2o4N65gBOmJtgRg69kmd8ZY?usp=sharing) with an example of using our classification ResNet18 model with your sample image with gesture "one" on it. 

You can pay attention to a part of the code with image preprocessing and running the model.


```python
image = Image.open("path/to/one.png")

image_resized = ImageOps.pad(image, tuple([224, 224]), color=(0, 0, 0))
image_tensor = F.pil_to_tensor(image_resized)
image_tensor = F.convert_image_dtype(image_tensor)

images = torch.stack(list(image.to(device) for image in [image_tensor]))

predicts = model(images)
```

You can also check if you are loading classifier pre-trained weights correctly in this part:

```python
model = ResNet(num_classes = 19, restype = "ResNet18")
model.load_state_dict(torch.load("/path/to/ResNet18/weights")["state_dict"])
model.eval()
```

Weights for ResNet18 are available via [link](https://sc.link/KEnx)
Google collab inference example is available via [link](https://colab.research.google.com/drive/1nXsDJGkD-2o4N65gBOmJtgRg69kmd8ZY?usp=sharing)

**Comment by explorer66** [comment]
I am really thankful for your help.After reading your example codes,I finally solve my problem.I realized that my image preprocessing codes have something different from yours.And now I can get the correct results.Thanks very much!
