### ISSUE TITLE
SSDLite onnx file [Request]

### ISSUE THREAD

**Issue by 1412kauti** [hukenovs/hagrid#23]
Request for the onnx file of the SSDLite.pth detector provided in the description... Thanks

**Comment by anotherhelloworld** [comment]
Hello, @1412kauti! 

We create a [google collab notebook](https://colab.research.google.com/drive/1pfooFyBpL7D_pe_AJthwX_uE4hMCkGqU?usp=sharing) with an example of exporting our SSDLite model onnx format. Therefore, you can use this notebook to get a model in onnx format and modify this code as you wish.

**Comment by nagadit** [comment]
I am closing this issue, but feel free to reopen it if you feel like it has not been resolved.
