### ISSUE TITLE
How to transform those json to yolo

### ISSUE THREAD

**Issue by 0coldmoon0** [hukenovs/hagrid#24]
I'm new here.I want to use yolov7 to training my model,but i don't know how to transform those json to yolo(.txt)

**Comment by nagadit** [comment]
#25 added

We checked the converter and trained the model in the [yolo](https://github.com/WongKinYiu/yolov7) repository.

I am closing this issue, but feel free to reopen it if you feel like it has not been resolved.

**Comment by 0coldmoon0** [comment]
This is my first time to find suitable dataset and train model.So,i want to verify how to use it.
If i want to train one or two hand gestures of entire dataset such as "call" and "dislike".Should i create a folder called"
A" with "call.annotations" and "dislike.annotations" and another flolder called"B" with relevant  total images.Then modify "converter_config.yaml" including correct path and targets. Finally,run "hagrid_to_yolo.py". Is it right?

**Comment by nagadit** [comment]
[how to run](https://github.com/hukenovs/hagrid#converters) 

if you want to train one or two hand gestures, just remove unnecessary from [config](https://github.com/hukenovs/hagrid/blob/master/converters/converter_config.yaml)
