### ISSUE TITLE
Pre-trained Models cannot be accessed

### ISSUE THREAD

**Issue by VBernasconi** [hukenovs/hagrid#26]
Hi, I am trying to access the pre-trained models but it seems that all links are broken.

**Comment by hukenovs** [comment]
Hi. We checked access to the models from several VPNs (EU, US, CN regions) and it works. Can you try downloading again or provide some information about your region/location?

**Comment by Suvi-dha** [comment]
Hi, I am downloading it from India, and I am getting this error:
`This XML file does not appear to have any style information associated with it. The document tree is shown below.

<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Resource>b-ws-620xz-pd11-jux/hagrid/hagrid_models_new/SSDLite_MobilenetV3_small.pth</Resource>
<RequestId>0a0b98bb:18cef1ec989:423b:4a8</RequestId>
</Error>`

**Comment by nagadit** [comment]
@Suvi-dha Thank you for your comment! The links are now working correctly

**Comment by AntonNuzhdin** [comment]
I am closing this issue, but feel free to reopen it if you feel like it has not been resolved.
