### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 64: invalid start byte

### ISSUE THREAD

**Issue by 1412kauti** [hukenovs/hagrid#30]
```
(hands_ai_proj) PS C:\Users\kauti\Desktop\hands_ai_projv2\hands_ai_proj\hagrid-master> python .\demo.py -p .\SSDLite_MobilenetV3_small.pth --landmarks
Traceback (most recent call last):
  File "C:\Users\kauti\Desktop\hands_ai_projv2\hands_ai_proj\hagrid-master\demo.py", line 148, in <module>
    conf = OmegaConf.load(args.path_to_config)
  File "C:\Users\kauti\.virtualenvs\hands_ai_proj-Ab44cTRZ\lib\site-packages\omegaconf\omegaconf.py", line 184, in load
    obj = yaml.load(f, Loader=get_yaml_loader())
  File "C:\Users\kauti\.virtualenvs\hands_ai_proj-Ab44cTRZ\lib\site-packages\yaml\__init__.py", line 79, in load
    loader = Loader(stream)
  File "C:\Users\kauti\.virtualenvs\hands_ai_proj-Ab44cTRZ\lib\site-packages\yaml\loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "C:\Users\kauti\.virtualenvs\hands_ai_proj-Ab44cTRZ\lib\site-packages\yaml\reader.py", line 85, in __init__
    self.determine_encoding()
  File "C:\Users\kauti\.virtualenvs\hands_ai_proj-Ab44cTRZ\lib\site-packages\yaml\reader.py", line 124, in determine_encoding
    self.update_raw()
  File "C:\Users\kauti\.virtualenvs\hands_ai_proj-Ab44cTRZ\lib\site-packages\yaml\reader.py", line 178, in update_raw
    data = self.stream.read(size)
  File "C:\Users\kauti\miniconda3\envs\threenine\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 64: invalid start byte
```
IM running this in Windows 11 on CPU in a conda environment

**Comment by 1412kauti** [comment]
I got the same issue in WSL 2 as well (Ubuntu 22.04 Python 3.9(pipenv))

**Comment by nagadit** [comment]
In the last update, we changed the launch of the demo, now it's done like this 
`python demo.py -p <PATH_TO_CONFIG> --landmarks`

Example of config you can find [here ](https://github.com/hukenovs/hagrid/blob/master/detector/config/default.yaml)
Just add checkpoint path and specify model name

**Comment by 1412kauti** [comment]
I made the suggested changes to the yaml file as seen here:

```
model:
  name: 'SSDLiteMobilenetV3_large'
  pretrained: False
  start_epoch: 0
  checkpoint: 'C:\Users\kauti\Desktop\hands_ai_proj\SSDLite_MobilenetV3_large.pth'
```
And I ran
`python .\hagrid\demo.py -p .\SSDLite_MobilenetV3_large.pth --landmarks`

I still get the same error

**Comment by 1412kauti** [comment]
Ya just noticed it. Thank You , Got it working.

Quick Question tho, how do I use the Yolov7 detector onnx ? dont see anything in utils.py for it.

and i dunno why...but the performance sure has dropped. since the last time I used Hagrid. will test it again on the usual hardware and update

**Comment by nagadit** [comment]
Use this [notebook](https://github.com/WongKinYiu/yolov7/blob/main/tools/YOLOv7-Dynamic-Batch-ONNXRUNTIME.ipynb), the input image size in our model is **(320,320)**

**Comment by nagadit** [comment]
I am closing this issue, but feel free to reopen it if you feel like it has not been resolved.

**Comment by hyhyni** [comment]
> ```
> (hands_ai_proj) PS C:\Users\kauti\Desktop\hands_ai_projv2\hands_ai_proj\hagrid-master> python .\demo.py -p .\SSDLite_MobilenetV3_small.pth --landmarks
> Traceback (most recent call last):
>   File "C:\Users\kauti\Desktop\hands_ai_projv2\hands_ai_proj\hagrid-master\demo.py", line 148, in <module>
>     conf = OmegaConf.load(args.path_to_config)
>   File "C:\Users\kauti\.virtualenvs\hands_ai_proj-Ab44cTRZ\lib\site-packages\omegaconf\omegaconf.py", line 184, in load
>     obj = yaml.load(f, Loader=get_yaml_loader())
>   File "C:\Users\kauti\.virtualenvs\hands_ai_proj-Ab44cTRZ\lib\site-packages\yaml\__init__.py", line 79, in load
>     loader = Loader(stream)
>   File "C:\Users\kauti\.virtualenvs\hands_ai_proj-Ab44cTRZ\lib\site-packages\yaml\loader.py", line 34, in __init__
>     Reader.__init__(self, stream)
>   File "C:\Users\kauti\.virtualenvs\hands_ai_proj-Ab44cTRZ\lib\site-packages\yaml\reader.py", line 85, in __init__
>     self.determine_encoding()
>   File "C:\Users\kauti\.virtualenvs\hands_ai_proj-Ab44cTRZ\lib\site-packages\yaml\reader.py", line 124, in determine_encoding
>     self.update_raw()
>   File "C:\Users\kauti\.virtualenvs\hands_ai_proj-Ab44cTRZ\lib\site-packages\yaml\reader.py", line 178, in update_raw
>     data = self.stream.read(size)
>   File "C:\Users\kauti\miniconda3\envs\threenine\lib\codecs.py", line 322, in decode
>     (result, consumed) = self._buffer_decode(data, self.errors, final)
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 64: invalid start byte
> ```
> 
> IM running this in Windows 11 on CPU in a conda environment

I got the same issue in 11, How did you solve this problem? Thank you very much.
