### ISSUE TITLE
Clarification on the confusion matrix

### ISSUE THREAD

**Issue by ennauata** [hukenovs/hagrid#31]
Hello,

Would appreciate some clarification on why the total number of samples for each class reported in the confusion matrix does not match the total number of samples for each class in the test set table. Am I missing anything? 

![image](https://user-images.githubusercontent.com/719481/228352097-cc400752-6651-49de-9c90-a70f2fe28baa.png)

![image](https://user-images.githubusercontent.com/719481/228352140-3d73dad3-351b-4d1f-bb26-71b121f3ebca.png)

Appreciate any help on this,
Best.

**Comment by karinakvanchiani** [comment]
Hi. We checked the calculations of classifier metrics and found an error in the data loader code. The repository code will be fixed soon. Updated confusion matrix is attached. Thank you for this comment!
![confusion_matrix_gesture (2)](https://user-images.githubusercontent.com/57008284/230032210-f36bdd28-b0e2-4ef6-8809-334d6d5bf7ec.jpg)

**Comment by nagadit** [comment]
I am closing this issue, but feel free to reopen it if you feel like it has not been resolved.
