### ISSUE TITLE
All download links are broken

### ISSUE THREAD

**Issue by EliasVansteenkiste** [hukenovs/hagrid#34]
@hukenovs, @nagadit all dataset sc.link download links are broken, even when using a VPN.

**Comment by hukenovs** [comment]
Hi @EliasVansteenkiste , we fixed all dataset links! Can you please check them again?

**Comment by FeliceSchena** [comment]
All links return 502 error.

**Comment by hukenovs** [comment]
@FeliceSchena @EliasVansteenkiste sorry for broken links and 502 errors. Try again please, it works!
