### ISSUE TITLE
Is it necessary to have landmarks when training new data?

### ISSUE THREAD

**Issue by LJHLJHLJHLJHL** [hukenovs/hagrid#41]
Is it necessary to have landmarks  when training new data?

**Comment by hukenovs** [comment]
No, you do not need the landmarks.

**Comment by LJHLJHLJHLJHL** [comment]
I'm sorry to ask you one more time, is there a way to train only the 3 gestures I want in the detector train and use them in the demo?

**Comment by AntonNuzhdin** [comment]
I am closing this issue, but feel free to reopen it if you feel like it has not been resolved.
