### ISSUE TITLE
thumbnail version

### ISSUE THREAD

**Issue by andy4120** [hukenovs/hagrid#45]
the image sets are  so big ,do you have a resized version or hand cropped part images?

**Comment by andy4120** [comment]
nice, looking forward for that

**Comment by hukenovs** [comment]
[HaGRID-512p](https://n-ws-620xz-pd11.s3pd11.sbercloud.ru/b-ws-620xz-pd11-jux/hagrid/hagrid/hagrid_512.zip) version - 13GB for full dataset.

**Comment by andy4120** [comment]
thank you so much!
