### ISSUE TITLE
How to finetune on yolov7_tiny?

### ISSUE THREAD

**Issue by bliblioscar** [hukenovs/hagrid#48]
Hi. I wonder if you can release your yolov7 checkpoint for us to finetune the detection model, because I can only get onnx file from your link.  And appreciate that if you can tell us how to run the train on yolov7. Thanks a lot!!

**Comment by bliblioscar** [comment]
> 

Thanks！I will try it！😊

**Comment by AntonNuzhdin** [comment]
I am closing this issue, but feel free to reopen it if you feel like it has not been resolved.
