### ISSUE TITLE
Wrong weights for ssdlite

### ISSUE THREAD

**Issue by Shanmukh-C** [hukenovs/hagrid#5]
![image](https://user-images.githubusercontent.com/85222764/184441452-bf0e22da-0732-48b8-9325-c7d55c033b31.png)
Hello we are getting this issue while running demo.py.

**Comment by anotherhelloworld** [comment]
Hello @Shanmukh-C 

Which version of torchvision and pytorch are you using? 

I notice that for detection demo.pya you should use weights of the SSDLite model that is available via [link](https://sc.link/YXg2).

**Comment by abhirajasp** [comment]
@Shanmukh-C raises a valid issue.
Any suggestions?
@anotherhelloworld the error shown above is using SSDLite model weights only.

**Comment by anotherhelloworld** [comment]
Hello @abhirajasp 

Maybe you are using a different version of torchvision pkg. We are using torchvision==0.12.0 from [requirements.txt](https://github.com/hukenovs/hagrid/blob/master/requirements.txt). 

Can you please provide a version of torchvision you are using?

**Comment by nagadit** [comment]
I am closing this issue, but feel free to reopen it if you feel like it has not been resolved.
