### ISSUE TITLE
when i use python -m converters.hagrid_to_coco --path_to_config <PATH> meet some problems

### ISSUE THREAD

**Issue by 2998848073** [hukenovs/hagrid#51]
usage: Convert Hagrid annotations to Yolo annotations format [--bbox_format BBOX_FORMAT] [--cfg CFG]
Convert Hagrid annotations to Yolo annotations format: error: unrecognized arguments: --path_to_config D:\deep\hagrid-master\ann_test

**Comment by AntonNuzhdin** [comment]
Hello! 

The argument for config called --cfg, as it described in "Converters" section in repo. Please try again with the correct argument name.

I am closing this issue, but feel free to reopen it if you feel like it has not been resolved.
