### ISSUE TITLE
I use yolov5 to train three gestures but there are many misjudgments. Is there any solution?

### ISSUE THREAD

**Issue by watertianyi** [hukenovs/hagrid#54]
Thank you for your timely answer. I only trained the three types of gesture data (marked red boxes) in Figure 1 below, a total of 30,000 images, 10,000 images for each type. The following is the training result Figure 2
Then we used the data of all gestures in Figure 1 above to test. The results were many misjudgments. How can we distinguish similar data sets?
![Image_20231021133746](https://github.com/ultralytics/yolov5/assets/29244715/f885585d-fb03-4ed4-a714-2b6edc6093a1)
 Figure 1
![Image_20231021134001](https://github.com/ultralytics/yolov5/assets/29244715/cc015b49-7c7a-43ac-a085-6249b3841b92)
 Figure 2
The misjudged data set is as shown below,
1. The real gesture is dislike which is misjudged as fist.
2. The real gesture is four, but it was misjudged as palm.
3. The real gesture was ok but was misjudged as peace.
![image](https://github.com/ultralytics/yolov5/assets/29244715/ce444aae-4977-4fb8-9322-dd6ee9755d60)
![image](https://github.com/ultralytics/yolov5/assets/29244715/26ab89ae-6da9-4255-ae3b-c6a3b821f422)
![image](https://github.com/ultralytics/yolov5/assets/29244715/930e4cd4-34b9-4341-ae0a-deac3a1dbd1a)

**Comment by karinakvanchiani** [comment]
Hello!

You need to add a no_gesture class to the classification. So that the model does not react to gestures that are not in your training data set, it is worth diversifying the no_gesture class with them.

**Comment by AntonNuzhdin** [comment]
Hello!

We conducted a lot of experiments using the YOLO model to train it on only a subset of gestures. However, we did not face any problems with recognition. Perhaps there are some bugs in your inference or training code.

Also, you could use our new YOLOv10x/n checkpoints, provided in our repository.

I am closing this issue, but feel free to reopen it if you feel like it has not been resolved.
