### ISSUE TITLE
Where to download the annotations of the lightweight version? 

### ISSUE THREAD

**Issue by ZC0102-shu** [hukenovs/hagrid#55]
Are they same to the original one?

**Comment by hukenovs** [comment]
Hi!
If you mean image crops, then it doesn't matter. The coordinates of the b-boxes are given in relative values (from 0 to 1).

**Comment by dwq4412** [comment]
> 你好！如果你的意思是图像裁剪，那没关系。b-box 的坐标以相对值（从 0 到 1）给出。

Hello！I think it means how to download the 21GB lightwight dataset，if it have

**Comment by eldgw0** [comment]
Help!This downloaded lightweight dataset does not contain annotations, did you find it over there.

**Comment by ZC0102-shu** [comment]
> Help!This downloaded lightweight dataset does not contain annotations, did you find it over there.
As the above reply says, the lower resolution version of the dataset should be available using the same annotations. 
 It's been so long ago that I forgot if I was referring to this low-resolution version...
