### ISSUE TITLE
handedness label (left/right)

### ISSUE THREAD

**Issue by pablovela5620** [hukenovs/hagrid#57]
I'm wondering if there's some missing annotation. I wanted to train a hand detection network that output bboxes + handedness classification (left v.s. right hand). In the paper I read that annotations include a `leading_hand` label
![image](https://github.com/hukenovs/hagrid/assets/25287427/6b119a57-da13-48dc-bb89-f04d7cc99302)
 
 I downloaded some of the annotation json, but could not find the handedness or leading hand annotation

**Comment by karinakvanchiani** [comment]
Hello!

We have decided to exclude the leading_hand label from the annotations (a paper will be updated on arxiv.com soon). However, you can get these marks yourself using heuristics: take any identical coordinate of two boxes and compare the values - the box with a lower value refers to the left hand in the photo (right in life), with a larger value - to the right (left in life).

**Comment by pablovela5620** [comment]
Great thanks, I also noticed that the V1 branch of the dataset still includes these labels. Incase anyone else is wondering where they can get it
