### ISSUE TITLE
The mAP of subsample dataset

### ISSUE THREAD

**Issue by moonlays** [hukenovs/hagrid#6]
Hello, I want to know the mAP value of the subsample dataset to verify whether I run the code correctly, thanks

**Comment by anotherhelloworld** [comment]
Hello @moonlays 

We got the following results for subsample dataset: map: 0.679301, map_50: 0.935013, map_75: 0.779909.

**Comment by moonlays** [comment]
Thanks.
And how long did it take you to train the  SSDLite model?

**Comment by anotherhelloworld** [comment]
Hello @moonlays 

We trained our model from scratch for 100 epochs and then pick model with the best mAP metric on valid dataset. According to our [paper](https://arxiv.org/pdf/2206.08219.pdf) the detector achieved the highest metric on epoch 67. Real training time depends on your GPU.

**Comment by nagadit** [comment]
I am closing this issue, but feel free to reopen it if you feel like it has not been resolved.
