### ISSUE TITLE
landmarks calibration or not

### ISSUE THREAD

**Issue by bluoluo** [hukenovs/hagrid#60]
Hello, Hagrid is a very great job.
I noticed that the 21 key points of hagrid v1 were annotated through MediaPipe. Has there been any manual calibration? Because I found that some key points were labeled incorrectly or in a wrong order, as shown in the figure.
Did the annotations in v2 delete landmarks?

![1](https://github.com/hukenovs/hagrid/assets/45422842/3ad69a78-016a-47dc-b684-fa54904f2d2d)
![2](https://github.com/hukenovs/hagrid/assets/45422842/8db85759-6d14-4591-a30c-e02384eb63e3)
![3](https://github.com/hukenovs/hagrid/assets/45422842/21d2b047-3a19-4422-9ce8-a7a93b04fd72)

**Comment by nagadit** [comment]
Hello @bluoluo!
Yes, we removed the annotations with landmarks because their quality was poor. 
No manual adjustments were made.

**Comment by bluoluo** [comment]
> Hello @bluoluo! Yes, we removed the annotations with landmarks because their quality was poor. No manual adjustments were made.

Okay, thank you very much!
