### ISSUE TITLE
Skeleton data availability

### ISSUE THREAD

**Issue by ggggg111** [hukenovs/hagrid#61]
Hello,

I would like to ask if skeleton data of the finger coordinates are available, as I'm conducting skeleton data analysis. I saw in the annotations file that exist the bounding boxes fields - it would be very helpful to have another one with the finger keypoints. If they aren't available, how do you plot the keypoints in the README demo, may I ask?

Thank you!

**Comment by hukenovs** [comment]
Hello!
We did not annotate the dataset with keypoints on purpose. But you can take a Mediapipe by Google (or other keypoint-based frameworks) and use it for synthetic markups.
