### ISSUE TITLE
How to calculate inference time

### ISSUE THREAD

**Issue by Thangtran27** [hukenovs/hagrid#67]
I read your paper about inference time. But I don't find the code to carry out calculating inference time. So how can I do that?
I'm looking forward to hearing from you!
![image](https://github.com/hukenovs/hagrid/assets/93766218/edcb26a0-53b4-40ac-8a54-5fe7cbcc1c9a)

**Comment by nagadit** [comment]
Hello @Thangtran27 !! 
You can measure the inference time using this code!

```python
time_list = []
for _ in range(100):
 st = time.time()
 out = model(input)
 time_list.append(time.time() - st)

print(np.mean(time_list)

```
