### ISSUE TITLE
Pytorch pth model for the yolov7 tiny

### ISSUE THREAD

**Issue by scottcali** [hukenovs/hagrid#68]
Hello,

     Could you please provide the Pytorch pth model for the yolov7 tiny? We need to add batch proccess.

     Many thanks!

-Scott

**Comment by nagadit** [comment]
Hello @scottcali !!
Sorry but we can't provide Pytorch pth model :C
But you can train your own model using source code from [Yolov7 repository](https://github.com/WongKinYiu/yolov7)
