### ISSUE TITLE
full frame vs non-full frame

### ISSUE THREAD

**Issue by scottcali** [hukenovs/hagrid#69]
Hello,

    Could you please tell us what are different between full frame and non-full frame?

    What is the input of the detectors? the 224x224 hand crop image?  

    Is the input of  full frame classifiers is the whole image, it can handle all hands in that images? Or just one hand in that image.

    "However, if you need a single gesture, you can use pre-trained full frame classifiers instead of detectors. To use full frame models, remove the no_gesture class ", could you give us example to show more info so that we can understand it?

    Thanks!

-Scott

**Comment by nagadit** [comment]
Hello @scottcali !
Full frame model takes a full frame as input and classifies only one gesture shown.

The detection model also takes as input a full frame from a 224x224 video, but predicts all gestures shown for their bounding boxes
