### ISSUE TITLE
PyTorch: File does not contain root module or state dictionary 

### ISSUE THREAD

**Issue by scottcali** [hukenovs/hagrid#70]
Hello,

    After I downloaded all the pth models, and open it with netron. They cannot be open and have all the same error:
      PyTorch: File does not contain root module or state dictionary 

    Could you please fix them? 

    Thanks!

-Scott

**Comment by nagadit** [comment]
Hello @scottcali !!
Can you please tell us in more detail in what cases and where you receive this error?

**Comment by scottcali** [comment]
Download Netron from https://github.com/lutzroeder/netron , Netron is a viewer for neural network, deep learning and machine learning models.

Download any pth model from https://github.com/hukenovs/hagrid

And open the model with Netron, you will see error, and the browser will go to this url: https://github.com/lutzroeder/netron/issues/543

**Comment by AntonNuzhdin** [comment]
Hello! 

With the HaGRIDv2 update and new checkpoints I had no problems while opening any model with https://netron.app/
Please, check it again 

I am closing this issue, but feel free to reopen it if you feel like it has not been resolved.
