### ISSUE TITLE
All dataset cannot be downloaded

### ISSUE THREAD

**Issue by scottcali** [hukenovs/hagrid#71]
Hi all,

     All dataset cannot be downloaded.

    Could you please fix those links?

    Thanks,

-Scott

**Comment by nagadit** [comment]
Hello @scottcali !!

We have double-checked the availability of all data and it is available)

What country are you from and what error did you encounter?

**Comment by scottcali** [comment]
United States. Probably our company blocked the site. However, i am able to
download all the models.

**Comment by hukenovs** [comment]
@scottcali try to use VPN (for Europe, or directly to Russia). It will fix your problem.
