### ISSUE TITLE
TypeError: Expected input images to be of floating type (in range [0, 1]), but found type torch.uint8 instead

### ISSUE THREAD

**Issue by hhsummerwind** [hukenovs/hagrid#80]
I got this error:
```
TypeError: Expected input images to be of floating type (in range [0, 1]), but found type torch.uint8 instead
```

when I run
```
python demo_ff.py -p configs/SSDLiteMobileNetV3Large.yaml
```

env:
cuda 11.7
python 3.1.10

absl-py                  2.1.0
albumentations           1.3.1
antlr4-python3-runtime   4.9.3
attrs                    24.2.0
certifi                  2024.8.30
cffi                     1.17.1
charset-normalizer       3.4.0
cmake                    3.31.1
coloredlogs              15.0.1
contourpy                1.3.1
cycler                   0.12.1
filelock                 3.16.1
flatbuffers              24.3.25
fonttools                4.55.0
humanfriendly            10.0
idna                     3.10
imageio                  2.36.1
Jinja2                   3.1.4
joblib                   1.4.2
kiwisolver               1.4.7
lazy_loader              0.4
lightning-utilities      0.11.9
lit                      18.1.8
MarkupSafe               3.0.2
matplotlib               3.9.2
mediapipe                0.10.3
mpmath                   1.3.0
networkx                 3.4.2
numpy                    1.24.2
nvidia-cublas-cu11       11.10.3.66
nvidia-cuda-cupti-cu11   11.7.101
nvidia-cuda-nvrtc-cu11   11.7.99
nvidia-cuda-runtime-cu11 11.7.99
nvidia-cudnn-cu11        8.5.0.96
nvidia-cufft-cu11        10.9.0.58
nvidia-curand-cu11       10.2.10.91
nvidia-cusolver-cu11     11.4.0.1
nvidia-cusparse-cu11     11.7.4.91
nvidia-nccl-cu11         2.14.3
nvidia-nvtx-cu11         11.7.91
omegaconf                2.3.0
onnx                     1.14.1
onnxruntime              1.15.1
opencv-contrib-python    4.8.0.76
opencv-python-headless   4.10.0.84
packaging                24.2
pandas                   2.0.3
pillow                   11.0.0
pip                      24.0
protobuf                 3.20.3
pycocotools              2.0.6
pycparser                2.22
pyparsing                3.2.0
python-dateutil          2.9.0.post0
pytz                     2024.2
PyYAML                   6.0.1
qudida                   0.0.4
requests                 2.32.3
scikit-image             0.24.0
scikit-learn             1.5.2
scipy                    1.14.1
setuptools               65.5.0
six                      1.16.0
sounddevice              0.5.1
sympy                    1.13.3
threadpoolctl            3.5.0
tifffile                 2024.9.20
torch                    2.0.0
torchaudio               2.0.1
torchmetrics             1.0.1
torchvision              0.15.1
tqdm                     4.66.1
triton                   2.0.0
typing_extensions        4.12.2
tzdata                   2024.2
urllib3                  2.2.3
wheel                    0.45.1

**Comment by AntonNuzhdin** [comment]
Hello! 

Perhaps, it is something wrong with library versions. 

Unfortunately, I was unable to reproduce your error. Try running the demo with the following library versions (I had no problems running it)

`
absl-py                2.1.0
albucore               0.0.21
albumentations         1.3.1
annotated-types        0.7.0
antlr4-python3-runtime 4.9.3
attrs                  24.2.0
certifi                2024.8.30
cffi                   1.17.1
charset-normalizer     3.4.0
coloredlogs            15.0.1
contourpy              1.3.1
cycler                 0.12.1
eval_type_backport     0.2.0
filelock               3.16.1
flatbuffers            24.3.25
fonttools              4.55.3
humanfriendly          10.0
idna                   3.10
imageio                2.36.1
Jinja2                 3.1.4
joblib                 1.4.2
kiwisolver             1.4.7
lazy_loader            0.4
lightning-utilities    0.11.9
MarkupSafe             3.0.2
matplotlib             3.9.4
mediapipe              0.10.5
mpmath                 1.3.0
networkx               3.4.2
numpy                  1.26.4
omegaconf              2.3.0
onnx                   1.14.1
onnxruntime            1.15.1
opencv-contrib-python  4.8.0.76
opencv-python          4.10.0.84
opencv-python-headless 4.10.0.84
packaging              24.2
pandas                 2.0.3
pillow                 11.0.0
pip                    24.2
protobuf               3.20.3
pycocotools            2.0.6
pycparser              2.22
pydantic               2.10.3
pydantic_core          2.27.1
pyparsing              3.2.0
python-dateutil        2.9.0.post0
pytz                   2024.2
PyYAML                 6.0.1
qudida                 0.0.4
requests               2.32.3
scikit-image           0.24.0
scikit-learn           1.6.0
scipy                  1.14.1
setuptools             75.1.0
simsimd                6.2.1
six                    1.17.0
sounddevice            0.5.1
stringzilla            3.11.1
sympy                  1.13.3
threadpoolctl          3.5.0
tifffile               2024.12.12
torch                  2.0.0
torchmetrics           1.0.1
torchvision            0.15.1
tqdm                   4.66.1
typing_extensions      4.12.2
tzdata                 2024.2
urllib3                2.2.3
wheel                  0.44.0
`
